search/urls.py
from django.conf.urls import url

from .views import SearchView





urlpatterns = [
    url(r'^$', SearchView.as_view(), name='default'),
]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin



from .views import home, HomeView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
    url(r'^search/', include('search.urls', namespace='search')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View

from categories.models import Category
from courses.models import Course, Lecture


class SearchView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        qs = None
        c_qs = None
        l_qs = None
        if query:
            lec_lookup = Q(title__icontains=query) \
                         | Q(description__icontains=query)
            # lookup2 =  Q(title__icontains=query) & Q(description__icontains=query)
            query_lookup = lec_lookup | Q(category__title__icontains=query) \
                           | Q(category__description__icontains=query) \
                           | Q(lecture__title__icontains=query) \

            qs = Course.objects.all().lectures().filter(
                        query_lookup
                    ).distinct()

            qs_ids = [x.id for x in qs]

            cat_lookup = Q(primary_category__in=qs_ids) | Q(secondary_category__in=qs_ids)
            c_qs = Category.objects.filter(lec_lookup | cat_lookup).distinct()
            l_qs = Lecture.objects.filter(lec_lookup).distinct()

        context = {"qs": qs, "c_qs": c_qs, "l_qs": l_qs}
        return render(request, "search/default.html", context)

search/templates/search/snippets/search_form.html
{% if not navbar %}
<form method='GET' action='{% url "search:default" %}'>
<input type='text' value='{{ request.GET.q }}' name='q' class='form-control' placeholder="Search..">
<!-- <input type='hidden' value='{{ request.GET.page }}' name='page' class='form-control'> -->
<button  class='btn btn-default' type='submit' ><i class='fa fa-search'></i> Search</button>
</form>

{% else %}
<form class="navbar-form navbar-left" method='GET' action='{% url "search:default" %}'>
<div class="form-group">
  <input type='text' value='{{ request.GET.q }}' name='q' class='form-control' placeholder="Search..">
</div>
<button  class='btn btn-default' type='submit' ><i class='fa fa-search'></i> Search</button>
</form>
{% endif %}