src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin



from .views import home, HomeView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
    url(r'^search/', include('search.urls', namespace='search')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.conf.urls import url
from django.contrib import admin


from .views import (
    VideoListView,
    VideoDetailView,
    VideoCreateView,
    VideoUpdateView,
    VideoDeleteView
    )

urlpatterns = [
    url(r'^$', VideoListView.as_view(), name='list'),
    url(r'^create/$', VideoCreateView.as_view(), name='create'),
    # url(r'^videos/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', VideoUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', VideoDeleteView.as_view(), name='delete'),

]

templates/base.html
{% load search_form %}
<!DOCTYPE html>
<html lang="en">
  <head>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Srvup{% endblock title %}</title>

    {% include 'defaults/head.html' %}
  </head>
  <body>

    <div class='container-fluid'>
      {% include 'navbar.html'%}
      {% block content %}
      {% endblock content %}
    </div>

   {% include 'defaults/scripts.html' %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello, {{ name }} {{ random_number }}!</h1>
  {% if request.user.is_authenticated %}
    <div class="container">
      Hi!
    </div>
  {% endif %}
{% endblock content %}

templates/navbar.html
{% load search_form %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'courses:list' %}">Srvup</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      {% search_form request True %}


      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'courses:list' %}">Courses</a></li>
        <li><a href="{% url 'categories:list' %}">Categories</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>